//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eccomerce.MiServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HelloWorld", ReplyAction="http://tempuri.org/IService1/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HelloWorld", ReplyAction="http://tempuri.org/IService1/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategorias", ReplyAction="http://tempuri.org/IService1/GetCategoriasResponse")]
        System.Data.DataSet GetCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategorias", ReplyAction="http://tempuri.org/IService1/GetCategoriasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        System.Data.DataSet GetProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProducto", ReplyAction="http://tempuri.org/IService1/AddProductoResponse")]
        string AddProducto(string nombre, string descripcion, int idCategoria, decimal precio, decimal precioOferta, int cantidad, string imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProducto", ReplyAction="http://tempuri.org/IService1/AddProductoResponse")]
        System.Threading.Tasks.Task<string> AddProductoAsync(string nombre, string descripcion, int idCategoria, decimal precio, decimal precioOferta, int cantidad, string imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProducto", ReplyAction="http://tempuri.org/IService1/UpdateProductoResponse")]
        string UpdateProducto(int idProducto, string nombre, string descripcion, int idCategoria, decimal precio, decimal precioOferta, int cantidad, string imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProducto", ReplyAction="http://tempuri.org/IService1/UpdateProductoResponse")]
        System.Threading.Tasks.Task<string> UpdateProductoAsync(int idProducto, string nombre, string descripcion, int idCategoria, decimal precio, decimal precioOferta, int cantidad, string imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProducto", ReplyAction="http://tempuri.org/IService1/DeleteProductoResponse")]
        void DeleteProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProducto", ReplyAction="http://tempuri.org/IService1/DeleteProductoResponse")]
        System.Threading.Tasks.Task DeleteProductoAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsuarios", ReplyAction="http://tempuri.org/IService1/GetUsuariosResponse")]
        System.Data.DataSet GetUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsuarios", ReplyAction="http://tempuri.org/IService1/GetUsuariosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUsuario", ReplyAction="http://tempuri.org/IService1/AddUsuarioResponse")]
        void AddUsuario(string nombreCompleto, string correo, string clave, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUsuario", ReplyAction="http://tempuri.org/IService1/AddUsuarioResponse")]
        System.Threading.Tasks.Task AddUsuarioAsync(string nombreCompleto, string correo, string clave, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUsuario", ReplyAction="http://tempuri.org/IService1/UpdateUsuarioResponse")]
        void UpdateUsuario(int idUsuario, string nombreCompleto, string correo, string clave, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUsuario", ReplyAction="http://tempuri.org/IService1/UpdateUsuarioResponse")]
        System.Threading.Tasks.Task UpdateUsuarioAsync(int idUsuario, string nombreCompleto, string correo, string clave, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUsuario", ReplyAction="http://tempuri.org/IService1/DeleteUsuarioResponse")]
        void DeleteUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUsuario", ReplyAction="http://tempuri.org/IService1/DeleteUsuarioResponse")]
        System.Threading.Tasks.Task DeleteUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVentas", ReplyAction="http://tempuri.org/IService1/GetVentasResponse")]
        System.Data.DataSet GetVentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVentas", ReplyAction="http://tempuri.org/IService1/GetVentasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetVentasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddVenta", ReplyAction="http://tempuri.org/IService1/AddVentaResponse")]
        void AddVenta(int idUsuario, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddVenta", ReplyAction="http://tempuri.org/IService1/AddVentaResponse")]
        System.Threading.Tasks.Task AddVentaAsync(int idUsuario, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVenta", ReplyAction="http://tempuri.org/IService1/UpdateVentaResponse")]
        void UpdateVenta(int idVenta, int idUsuario, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVenta", ReplyAction="http://tempuri.org/IService1/UpdateVentaResponse")]
        System.Threading.Tasks.Task UpdateVentaAsync(int idVenta, int idUsuario, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteVenta", ReplyAction="http://tempuri.org/IService1/DeleteVentaResponse")]
        void DeleteVenta(int idVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteVenta", ReplyAction="http://tempuri.org/IService1/DeleteVentaResponse")]
        System.Threading.Tasks.Task DeleteVentaAsync(int idVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDetalleVentas", ReplyAction="http://tempuri.org/IService1/GetDetalleVentasResponse")]
        System.Data.DataSet GetDetalleVentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDetalleVentas", ReplyAction="http://tempuri.org/IService1/GetDetalleVentasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDetalleVentasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDetalleVenta", ReplyAction="http://tempuri.org/IService1/AddDetalleVentaResponse")]
        void AddDetalleVenta(int idVenta, int idProducto, int cantidad, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDetalleVenta", ReplyAction="http://tempuri.org/IService1/AddDetalleVentaResponse")]
        System.Threading.Tasks.Task AddDetalleVentaAsync(int idVenta, int idProducto, int cantidad, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDetalleVenta", ReplyAction="http://tempuri.org/IService1/UpdateDetalleVentaResponse")]
        void UpdateDetalleVenta(int idDetalleVenta, int idVenta, int idProducto, int cantidad, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDetalleVenta", ReplyAction="http://tempuri.org/IService1/UpdateDetalleVentaResponse")]
        System.Threading.Tasks.Task UpdateDetalleVentaAsync(int idDetalleVenta, int idVenta, int idProducto, int cantidad, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDetalleVenta", ReplyAction="http://tempuri.org/IService1/DeleteDetalleVentaResponse")]
        void DeleteDetalleVenta(int idDetalleVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDetalleVenta", ReplyAction="http://tempuri.org/IService1/DeleteDetalleVentaResponse")]
        System.Threading.Tasks.Task DeleteDetalleVentaAsync(int idDetalleVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCategoria", ReplyAction="http://tempuri.org/IService1/CreateCategoriaResponse")]
        string CreateCategoria(string nombre, System.DateTime fechaCreacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCategoria", ReplyAction="http://tempuri.org/IService1/CreateCategoriaResponse")]
        System.Threading.Tasks.Task<string> CreateCategoriaAsync(string nombre, System.DateTime fechaCreacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCategoria", ReplyAction="http://tempuri.org/IService1/UpdateCategoriaResponse")]
        string UpdateCategoria(int idCategoria, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCategoria", ReplyAction="http://tempuri.org/IService1/UpdateCategoriaResponse")]
        System.Threading.Tasks.Task<string> UpdateCategoriaAsync(int idCategoria, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategoria", ReplyAction="http://tempuri.org/IService1/DeleteCategoriaResponse")]
        void DeleteCategoria(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategoria", ReplyAction="http://tempuri.org/IService1/DeleteCategoriaResponse")]
        System.Threading.Tasks.Task DeleteCategoriaAsync(int idCategoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Eccomerce.MiServicio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Eccomerce.MiServicio.IService1>, Eccomerce.MiServicio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetCategorias() {
            return base.Channel.GetCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCategoriasAsync() {
            return base.Channel.GetCategoriasAsync();
        }
        
        public System.Data.DataSet GetProductos() {
            return base.Channel.GetProductos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProductosAsync() {
            return base.Channel.GetProductosAsync();
        }
        
        public string AddProducto(string nombre, string descripcion, int idCategoria, decimal precio, decimal precioOferta, int cantidad, string imagen) {
            return base.Channel.AddProducto(nombre, descripcion, idCategoria, precio, precioOferta, cantidad, imagen);
        }
        
        public System.Threading.Tasks.Task<string> AddProductoAsync(string nombre, string descripcion, int idCategoria, decimal precio, decimal precioOferta, int cantidad, string imagen) {
            return base.Channel.AddProductoAsync(nombre, descripcion, idCategoria, precio, precioOferta, cantidad, imagen);
        }
        
        public string UpdateProducto(int idProducto, string nombre, string descripcion, int idCategoria, decimal precio, decimal precioOferta, int cantidad, string imagen) {
            return base.Channel.UpdateProducto(idProducto, nombre, descripcion, idCategoria, precio, precioOferta, cantidad, imagen);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProductoAsync(int idProducto, string nombre, string descripcion, int idCategoria, decimal precio, decimal precioOferta, int cantidad, string imagen) {
            return base.Channel.UpdateProductoAsync(idProducto, nombre, descripcion, idCategoria, precio, precioOferta, cantidad, imagen);
        }
        
        public void DeleteProducto(int idProducto) {
            base.Channel.DeleteProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task DeleteProductoAsync(int idProducto) {
            return base.Channel.DeleteProductoAsync(idProducto);
        }
        
        public System.Data.DataSet GetUsuarios() {
            return base.Channel.GetUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUsuariosAsync() {
            return base.Channel.GetUsuariosAsync();
        }
        
        public void AddUsuario(string nombreCompleto, string correo, string clave, string rol) {
            base.Channel.AddUsuario(nombreCompleto, correo, clave, rol);
        }
        
        public System.Threading.Tasks.Task AddUsuarioAsync(string nombreCompleto, string correo, string clave, string rol) {
            return base.Channel.AddUsuarioAsync(nombreCompleto, correo, clave, rol);
        }
        
        public void UpdateUsuario(int idUsuario, string nombreCompleto, string correo, string clave, string rol) {
            base.Channel.UpdateUsuario(idUsuario, nombreCompleto, correo, clave, rol);
        }
        
        public System.Threading.Tasks.Task UpdateUsuarioAsync(int idUsuario, string nombreCompleto, string correo, string clave, string rol) {
            return base.Channel.UpdateUsuarioAsync(idUsuario, nombreCompleto, correo, clave, rol);
        }
        
        public void DeleteUsuario(int idUsuario) {
            base.Channel.DeleteUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task DeleteUsuarioAsync(int idUsuario) {
            return base.Channel.DeleteUsuarioAsync(idUsuario);
        }
        
        public System.Data.DataSet GetVentas() {
            return base.Channel.GetVentas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetVentasAsync() {
            return base.Channel.GetVentasAsync();
        }
        
        public void AddVenta(int idUsuario, decimal total) {
            base.Channel.AddVenta(idUsuario, total);
        }
        
        public System.Threading.Tasks.Task AddVentaAsync(int idUsuario, decimal total) {
            return base.Channel.AddVentaAsync(idUsuario, total);
        }
        
        public void UpdateVenta(int idVenta, int idUsuario, decimal total) {
            base.Channel.UpdateVenta(idVenta, idUsuario, total);
        }
        
        public System.Threading.Tasks.Task UpdateVentaAsync(int idVenta, int idUsuario, decimal total) {
            return base.Channel.UpdateVentaAsync(idVenta, idUsuario, total);
        }
        
        public void DeleteVenta(int idVenta) {
            base.Channel.DeleteVenta(idVenta);
        }
        
        public System.Threading.Tasks.Task DeleteVentaAsync(int idVenta) {
            return base.Channel.DeleteVentaAsync(idVenta);
        }
        
        public System.Data.DataSet GetDetalleVentas() {
            return base.Channel.GetDetalleVentas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDetalleVentasAsync() {
            return base.Channel.GetDetalleVentasAsync();
        }
        
        public void AddDetalleVenta(int idVenta, int idProducto, int cantidad, decimal total) {
            base.Channel.AddDetalleVenta(idVenta, idProducto, cantidad, total);
        }
        
        public System.Threading.Tasks.Task AddDetalleVentaAsync(int idVenta, int idProducto, int cantidad, decimal total) {
            return base.Channel.AddDetalleVentaAsync(idVenta, idProducto, cantidad, total);
        }
        
        public void UpdateDetalleVenta(int idDetalleVenta, int idVenta, int idProducto, int cantidad, decimal total) {
            base.Channel.UpdateDetalleVenta(idDetalleVenta, idVenta, idProducto, cantidad, total);
        }
        
        public System.Threading.Tasks.Task UpdateDetalleVentaAsync(int idDetalleVenta, int idVenta, int idProducto, int cantidad, decimal total) {
            return base.Channel.UpdateDetalleVentaAsync(idDetalleVenta, idVenta, idProducto, cantidad, total);
        }
        
        public void DeleteDetalleVenta(int idDetalleVenta) {
            base.Channel.DeleteDetalleVenta(idDetalleVenta);
        }
        
        public System.Threading.Tasks.Task DeleteDetalleVentaAsync(int idDetalleVenta) {
            return base.Channel.DeleteDetalleVentaAsync(idDetalleVenta);
        }
        
        public string CreateCategoria(string nombre, System.DateTime fechaCreacion) {
            return base.Channel.CreateCategoria(nombre, fechaCreacion);
        }
        
        public System.Threading.Tasks.Task<string> CreateCategoriaAsync(string nombre, System.DateTime fechaCreacion) {
            return base.Channel.CreateCategoriaAsync(nombre, fechaCreacion);
        }
        
        public string UpdateCategoria(int idCategoria, string nombre) {
            return base.Channel.UpdateCategoria(idCategoria, nombre);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCategoriaAsync(int idCategoria, string nombre) {
            return base.Channel.UpdateCategoriaAsync(idCategoria, nombre);
        }
        
        public void DeleteCategoria(int idCategoria) {
            base.Channel.DeleteCategoria(idCategoria);
        }
        
        public System.Threading.Tasks.Task DeleteCategoriaAsync(int idCategoria) {
            return base.Channel.DeleteCategoriaAsync(idCategoria);
        }
    }
}
